spring:
  application:
    name: jwtsecurity_login

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_spring_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: auth_user
    password: qwer1234!

  jpa:
    hibernate:
      ddl-auto: update # Entity 의 멤버변수가 변하면 자동으로 데이터베이스의 테이블도 갱신해준다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  mvc:
    throw-exception-if-no-handler-found: true # @ExceptionHandler 에서 예외처리를 찾아라
  #  web:
  #    resources:
  #      add-mappings: false # 404.html 출력 하지 마라

  data:
    redis:
      host: localhost
      port: 6379
      password: mjc813pass
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${YOUR_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-url: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: ${YOUR_GITHUB_CLIENT_ID}
            client-secret: ${YOUR_GITHUB_CLIENT_SECRET}
            scope:
              - read
              - profile
            redirect-url: "{baseUrl}/login/oauth2/code/{registrationId}"

  mustache:
    prefix: classpath:/templates/    # 템플릿 파일 경로
    suffix: .html                    # 파일 확장자 (.mustache, .html 등으로 변경 가능)
    servlet:
      content-type: text/html       # 응답 Content-Type
    charset: UTF-8                  # 한글 인코딩 설정
    cache: false                    # 개발 환경에서는 false, 운영 환경에서는 true 권장

server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

myapp:
  jwt:
    secret: thisismyjwtsecretkey!123456abcdef
    expireAccessToken: 600 # 30 분 * 60 초
    expireRefreshToken: 1209600 # 14 일 * 24 시 * 60 분 * 60 초

